// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 0.1.8
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "/0.1.8/WalkMeEditor.xcframework.zip",
            checksum: "8b8c479f258e8a6680585d6c621f7622ca148a270f48306cb4bea1570ef1a44a"
        )
    ]
)
