// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 0.1.3
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk-editor/releases/download/0.1.3/WalkMeEditor.xcframework.zip",
            checksum: "ad0b59e9c89a8a30e4323f3b265e5b59f3c7b340db941844dde0626f710bd4a0"
        )
    ]
)
