// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 0.2.3
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk-editor/releases/download/0.2.3/WalkMeEditor.xcframework.zip",
            checksum: "06fc4dae254b5e00c413c66d17530240509b72bbbe904a0235b74594c2c1667e"
        )
    ]
)
